# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T12:12:43+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyQuery, BaseSecurity
from pydantic import conint

from models import (
    Account,
    Country,
    Device,
    Error,
    Headers,
    PageError,
    Proxy,
    SelectedAreas,
    Selectors,
)

app = MCPProxy(
    contact={
        'email': 'support@webscraping.ai',
        'name': 'WebScraping.AI Support',
        'url': 'https://webscraping.ai',
    },
    description='A client for https://webscraping.ai API. It provides a web scaping automation API with Chrome JS rendering, rotating proxies and builtin HTML parsing.',
    title='WebScraping.AI',
    version='2.0.7',
    servers=[{'url': 'https://api.webscraping.ai'}],
)


@app.get(
    '/account',
    description=""" Always returns JSON """,
    tags=['account_info_management'],
    security=[
        APIKeyQuery(name="api_key"),
    ],
)
def account():
    """
    Information about your account calls quota
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/html',
    description=""" Returns just HTML on success, JSON on error """,
    tags=['webpage_html_retrieval'],
    security=[
        APIKeyQuery(name="api_key"),
    ],
)
def get_h_t_m_l(
    url: str,
    headers: Optional[Headers] = None,
    timeout: Optional[conint(ge=1, le=30000)] = 10000,
    js: Optional[bool] = True,
    js_timeout: Optional[conint(ge=1, le=20000)] = 2000,
    proxy: Optional[Proxy] = 'datacenter',
    country: Optional[Country] = 'us',
    device: Optional[Device] = 'desktop',
    error_on_404: Optional[bool] = False,
    error_on_redirect: Optional[bool] = False,
):
    """
    Page HTML by URL
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/selected',
    description=""" Returns just HTML on success, JSON on error """,
    tags=['webpage_html_retrieval'],
    security=[
        APIKeyQuery(name="api_key"),
    ],
)
def get_selected(
    selector: Optional[str] = None,
    url: str = ...,
    headers: Optional[Headers] = None,
    timeout: Optional[conint(ge=1, le=30000)] = 10000,
    js: Optional[bool] = True,
    js_timeout: Optional[conint(ge=1, le=20000)] = 2000,
    proxy: Optional[Proxy] = 'datacenter',
    country: Optional[Country] = 'us',
    device: Optional[Device] = 'desktop',
    error_on_404: Optional[bool] = False,
    error_on_redirect: Optional[bool] = False,
):
    """
    HTML of a selected page area by URL and CSS selector
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/selected-multiple',
    description=""" Always returns JSON """,
    tags=['webpage_html_retrieval'],
    security=[
        APIKeyQuery(name="api_key"),
    ],
)
def get_selected_multiple(
    selectors: Optional[Selectors] = None,
    url: str = ...,
    headers: Optional[Headers] = None,
    timeout: Optional[conint(ge=1, le=30000)] = 10000,
    js: Optional[bool] = True,
    js_timeout: Optional[conint(ge=1, le=20000)] = 2000,
    proxy: Optional[Proxy] = 'datacenter',
    country: Optional[Country] = 'us',
    device: Optional[Device] = 'desktop',
    error_on_404: Optional[bool] = False,
    error_on_redirect: Optional[bool] = False,
):
    """
    HTML of multiple page areas by URL and CSS selectors
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
