# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T12:12:43+00:00

from __future__ import annotations

from enum import Enum
from typing import Dict, List, Optional

from pydantic import BaseModel, Field, RootModel


class Account(BaseModel):
    remaining_api_calls: Optional[int] = Field(
        None, description='Remaining API calls quota'
    )
    remaining_concurrency: Optional[int] = Field(
        None, description='Remaining concurrent requests'
    )
    resets_at: Optional[int] = Field(
        None, description='Next billing cycle start time (UNIX timestamp)'
    )


class Error(BaseModel):
    message: Optional[str] = Field(None, description='Error description')


class PageError(BaseModel):
    status_code: Optional[int] = Field(
        None, description='Response HTTP status code (403, 500, etc)'
    )
    status_message: Optional[str] = Field(
        None, description='Response HTTP status message'
    )


class SelectedAreas(RootModel[List[str]]):
    root: List[str] = Field(
        ...,
        description='Array of elements matched by selectors',
        title='HTML for selected page areas',
    )


class Proxy(Enum):
    datacenter = 'datacenter'
    residential = 'residential'


class Country(Enum):
    us = 'us'
    gb = 'gb'
    de = 'de'
    it = 'it'
    fr = 'fr'
    ca = 'ca'
    es = 'es'
    ru = 'ru'
    jp = 'jp'
    kr = 'kr'


class Device(Enum):
    desktop = 'desktop'
    mobile = 'mobile'
    tablet = 'tablet'


class Headers(RootModel[Optional[Dict[str, str]]]):
    root: Optional[Dict[str, str]] = None


class Selectors(RootModel[List[str]]):
    root: List[str]
